In [3]:
import torch
import numpy as np

In [4]:
arr = [[1, 2],[3, 4]]

In [5]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [6]:
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

## Create Matrices with default values

In [7]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [8]:
torch.rand((2,2))

tensor([[0.3975, 0.1576],
        [0.3089, 0.3694]])

In [12]:
torch.manual_seed(42)
torch.rand(2,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [13]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [14]:
torch.manual_seed(42)
torch.rand(2,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [17]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

## Numpy and Torch Bridge

### Numpy to Torch

In [18]:
np_array = np.ones((2,2))

In [19]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [20]:
tensor_torch = torch.from_numpy(np_array)

In [21]:
print(tensor_torch)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [23]:
np_array_new = np.ones((2,2), dtype=np.int8)
# torch.from_numpy(np_array_new)

In [24]:
np_array_new = np.ones((2,2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]])

In [25]:
np_array_new = np.ones((2,2), dtype=np.int32)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [26]:
np_array_new = np.ones((2,2), dtype=np.float)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

### Torch To Numpy

In [27]:
torch_tensor = torch.ones(2,2)

In [28]:
type(torch_tensor)

torch.Tensor

In [29]:
torch_to_numpy = torch_tensor.numpy()

In [30]:
type(torch_to_numpy)

numpy.ndarray

In [31]:
print(torch.cuda.is_available())

False


### Resizing tensor

In [32]:
a = torch.ones(2,2)

In [33]:
print(a.size())

torch.Size([2, 2])


In [34]:
a.view(4)

tensor([1., 1., 1., 1.])

In [35]:
a.view(4).size()

torch.Size([4])

### 

In [36]:
b = torch.ones(2,2)

In [37]:
print(a+b)

tensor([[2., 2.],
        [2., 2.]])


In [41]:
a = torch.Tensor([[1,2,3,4,5,6,7,8,9
                   
                   ,10], [1,2,3,4,5,6,7,8,9,10]])

In [42]:
print(a.mean(dim=0))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [43]:
print(a.mean(dim=1))

tensor([5.5000, 5.5000])


In [44]:
print(a)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])


### Pytorch Variables and Gradients

In [46]:
from torch.autograd import Variable

In [47]:
a = Variable(torch.ones(2,2), requires_grad=True)

In [48]:
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [49]:
x = Variable(torch.ones(2), requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

In [50]:
y = 5 * (x + 1) ** 2

In [51]:
y

tensor([20., 20.], grad_fn=<MulBackward>)

In [52]:
o = (1/2)* torch.sum(y)
o

tensor(20., grad_fn=<MulBackward>)